### PR TITLE
Update JDK and Apache Maven

### LINKED ISSUE #83: Error in 1.4.0 with decompiling
I got this error when trying to decompile a map.
[error] BspSourceFrame: Fatal BSPSource error, caused by java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	at info.ata4.bsplib.lump.AbstractLump.setBuffer(AbstractLump.java:68)
	at info.ata4.bsplib.BspFile.loadLumps(BspFile.java:349)
	at info.ata4.bsplib.BspFile.load(BspFile.java:160)
	at info.ata4.bsplib.BspFile.load(BspFile.java:180)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:107)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:72)
	at info.ata4.bspsrc.gui.BspSourceFrame$4.run(BspSourceFrame.java:359)

The map successfully decompiles in BSPSource 1.3.24 without issues.

### PR DESCRIPTION
**Pull request by rihi**
In order to use JDK 9 or later for compiling bspsrc, but still compile for Java 8, the Apache Maven Compiler Plugin has been configured to use the '--release' command-line option instead of '-source' and '-target' with javac. This ensures that the compiled program will not accidentally use APIs that are only available in the Java version corresponding to the JDK in use.

The Apache Maven Compiler Plugin and the Apache Maven Shade Plugin have also been updated to their current versions.

Fixes #83

### CODE REVIEW

**Comment by rihi** [comment]
On the flipside this also means, that jdk9 or above is required for compiling!

**Comment by rihi** [comment]
@ata4

**Comment by ata4** [comment]
That's okay. I've indeed compiled it for Java 9, thinking it's widespread now. But since the code doesn't really use any new features, making it compatible with 8 is fine.

**Comment by rihi** [comment]
Thanks, I guess because a lot of people dont use java often, there is no real reason to update for them.
<sub>Oh and btw don't mind my random comment which closed the pull request temporarily. I misclicked when trying to cancel a comment.</sub>
