### ISSUE TITLE
Error in 1.4.0 with decompiling

### ISSUE THREAD

**Issue by TiberiumFusion** [ata4/bspsrc#83]
I got this error when trying to decompile a map.
[error] BspSourceFrame: Fatal BSPSource error, caused by java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	at info.ata4.bsplib.lump.AbstractLump.setBuffer(AbstractLump.java:68)
	at info.ata4.bsplib.BspFile.loadLumps(BspFile.java:349)
	at info.ata4.bsplib.BspFile.load(BspFile.java:160)
	at info.ata4.bsplib.BspFile.load(BspFile.java:180)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:107)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:72)
	at info.ata4.bspsrc.gui.BspSourceFrame$4.run(BspSourceFrame.java:359)

The map successfully decompiles in BSPSource 1.3.24 without issues.

**Comment by rihi** [comment]
Hmmm, seems like the when building the jar some kind of mistake was made, which produced incorrect bytecode.

@ata4 you may have to check how you build the jar. My guess is that you accidentally used a build configuration for java 9 or something, because a simple `mvn package` works for me. (I have java 8 installed, not sure if that changes the packaging).

**Comment by rihi** [comment]
@TiberiumFusion As a quick workaround you could install java 9 and execute the jar with that, as that _should_ work.

**Comment by SethTooQuick** [comment]
I can vouch, I'm getting this same error.

**Comment by ata4** [comment]
I've updated the build, which should hopefull run with Java 8 as well.

**Comment by rihi** [comment]
Works for me now! 👍
